version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "monthly"
      time: "04:00"
      timezone: America/Argentina/Buenos_Aires
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "04:00"
      timezone: America/Argentina/Buenos_Aires
