name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"

permissions:
  pull-requests: write

jobs:
  flatpak:
    name: Flatpak builder
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.3
      with:
        bundle: viper.flatpak
        manifest-path: org.viper.terminal.dev.yml
        cache-key: flatpak-builder-${{ github.sha }}
  check:
    name: Check
    runs-on: ubuntu-22.04
    steps:
      - name: Install additional linux dependencies
        run: |
          sudo apt update -y
          sudo apt install -y build-essential libgtk-4-dev
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --verbose
      - name: Check without default features
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --no-default-features --verbose
  typos:
    name: Typos
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check typos
        uses: crate-ci/typos@master

  clippy:
    name: Lints
    runs-on: ubuntu-22.04
    steps:
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check the lints
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --tests --verbose -- -D warnings
      - name: Check the pedantic lints
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --verbose -- -W clippy::pedantic

  rustfmt:
    name: Formatting
    runs-on: ubuntu-22.04
    steps:
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check the formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check --verbose

  doctest:
    name: Doctests
    runs-on: ubuntu-22.04
    steps:
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check the formatting
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc
  profiler:
    name: Run profiler
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run profiler
        run: cargo run --profile bench --features profiler -- --no-exec
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: viper.${{ github.run_id }}-profiler-report
          path: viper.**.flamegraph.svg
