name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"

permissions:
  pull-requests: write

jobs:
  flatpak:
    name: Flatpak builder
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.4
      with:
        bundle: viper.flatpak
        manifest-path: org.viper.terminal.dev.yml
        cache-key: flatpak-builder-${{ github.sha }}
